name: cydia repository
bio: a cydia repository created by jmd0x

description: a cydia repository created by jmd0x
external-image: true
picture: assets/images/cydia.jpg

url: https://jmd0x.github.io/cydia/

permalink: /:title/


authors:
    repo:
        name: cydia repository
        bio: a cydia repository created by jmd0x
        external-image: true
        picture: assets/images/cydia.jpg
    repo:
        name: cydia repository
        bio: a cydia repository created by nostalgia
        external-image: true
        picture: assets/images/cydia.jpg

width: normal



email: jmd0x@github.io
github: jmd0x

home: true
cydia: true


read-time: true
show-tags: true
related: true
post-advance-links: [blog]
show-author: true
animation: true



plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin

jekyll-mentions:
    base_url: https://github.com
