name: nostalg1a.github.io/cydia
bio: public cydia repo

description: public cydia repo

external-image: true
picture: assets/images/dragon.jpg

url: https://nostalg1a.github.io

permalink: /:title/

email: nostalg1a@outlook.com

authors:
    nostalg1a.github.io/cydia:
        name: nostalg1a.github.io/cydia
        bio: public cydia repo
        external-image: true
        picture: assets/images/dragon.jpg
        twitter: nostalg1a
    nostalg1a.github.io/cydia:
        name: nostalg1a.github.io/cydia
        bio: public cydia repo
        external-image: true
        picture: assets/images/dragon.jpg
        twitter: nostalg1a

width: normal




github: true
cydia: true
packages: true




read-time: true

show-tags: true

related: true

post-advance-links: [blog]

show-author: true

animation: true

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin

jekyll-mentions:
    base_url: https://github.com
