name: cydia
bio: repo

description: repo

external-image: true
picture: assets/images/dragon.jpg

url: https://nostalg1a.github.io

permalink: /:title/

email: nostalg1a@outlook.com
github: nostalg1a
cydia: nostalg1a.github.io/cydia

authors:
    cydia:
        name: cydia
        bio: repo
        external-image: true
        picture: assets/images/dragon.jpg
    cydia:
        name: cydia
        bio: repo
        external-image: true
        picture: assets/images/dragon.jpg

# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

github: true
cydia: true
packages: true
projects: true

read-time: true

show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [home]

show-author: true

animation: true

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin

jekyll-mentions:
    base_url: https://github.com
